---
runtime:
  # Set a local antora cache dir for git repositories and UI components
  cache_dir: ./.cache/antora
  fetch: true
site:
  title: Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.opennms.com/
  start_page: start-page::index.adoc
  robots: allow
content:
  sources:
  # Generic start page
  - url: .
    start_path: start-page
    branches: HEAD
  - url: https://github.com/OpenNMS/opennms.git
    start_path: docs
    branches:
      - master
      - master-29
  - url: https://GITHUB_PRIME_TOKEN@github.com/OpenNMS/opennms-prime.git
    start_path: docs
    branches:
      - 'master-*'
      - '!master-2020'
      - '!master-2019'
      - '!master-2018'
      - '!master-2017'
      - '!master-2016'
      - '!master-2015'
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/opennms/opennms-helm.git
    start_path: docs
    branches:
      - develop
      - /^release-.*/
      - /^main-.*/
    tags:
      - v*
      - '!v8.0.0'
      - '!v5.0.1'
      - '!v5.0.0'
      - '!v4.*'
      - '!v3.*'
      - '!v2.*'
      - '!v1.*'
  - url: https://github.com/OpenNMS/alec.git
    start_path: docs
    branches:
      - develop
      - /^release-.*/
    tags:
      - v*
      - '!v2.0.0.alpha0' # same SNAPSHOT version as another branch
      - '!v1.1.1' # Tag v1.1.1 has version number 1.1.1-SNAPSHOT use v1.1.1-doc instead
      - '!v1.1.1-rebuild' # I thought I needed to remake the debs, but I did not
  - url: https://github.com/OpenNMS/opennms-provisioning-integration-server.git
    start_path: docs
    branches:
      - release-*
      - '!release-1.1*'
      - '!release-1.0*'
  - url: https://github.com/OpenNMS/opennms-js.git
    start_path: docs-src
    branches: develop
    tags:
    - v*
    - '!v0.*'
    - '!v1.*'
    - '!v2.0.0'
    - '!v2.0.1'
    - '!v2.0.2'
    - '!v2.5.0'
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.0.1/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    distribution: 'Horizon'
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
