---
site:
  title: OpenNMS Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.opennms.com
  start_page: helm::index.adoc
  robots: allow
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/opennms/opennms-helm.git
    branches: master
    start_path: docs
  - url: https://github.com/OpenNMS/alec.git
    branches: ~
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://mirror.opennms.eu/share/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    stem: latexmath
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
