---
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
git:
  fetch_concurrency: 1
runtime:
  # Set a local antora cache dir for git repositories and UI components
  cache_dir: ./.cache/antora
  fetch: true
site:
  title: Docs
  # the 404 page and sitemap files only get generated when the url property is set
  # TODO MVR provide url: docs.bluebird.community
  url: https://docs.bluebird.community/
  keys:
    # TODO MVR update this
    google_analytics: 'G-WR2RML9P8J'
  start_page: start-page::index.adoc
  # the wildcarded directories will exclude everything in that path, so be aware when adding new files that do have h1 to those directories. Wildcards used to allow for Meridian/Horizon and different versions of each.
  robots: |
    User-agent: *
    Disallow: /*/*/deployment/core/centos-rhel/
    Disallow: /*/*/deployment/core/centos-rhel7/
    Disallow: /*/*/deployment/core/centos-rhel8/
    Disallow: /*/*/deployment/core/centos-rhel9/
    Disallow: /*/*/deployment/core/debian-ubuntu/
    Disallow: /*/*/deployment/core/debian/
    Disallow: /*/*/deployment/core/docker/
    Disallow: /*/*/deployment/core/message-broker/
    Disallow: /*/*/deployment/core/ubuntu/
    Disallow: /*/*/deployment/minion/centos-rhel7/
    Disallow: /*/*/deployment/minion/centos-rhel8/
    Disallow: /*/*/deployment/minion/centos-rhel9/
    Disallow: /*/*/deployment/minion/debian/
    Disallow: /*/*/deployment/minion/docker/
    Disallow: /*/*/deployment/minion/message-broker/
    Disallow: /*/*/deployment/minion/ubuntu/
    Disallow: /*/*/deployment/opentracing/core.adoc
    Disallow: /*/*/deployment/opentracing/minion.adoc
    Disallow: /*/*/deployment/opentracing/sentinel.adoc
    Disallow: /*/*/deployment/repos/rhel-centos/
    Disallow: /*/*/deployment/sentinel/runtime/centos-rhel/
    Disallow: /*/*/deployment/sentinel/runtime/centos-rhel7/
    Disallow: /*/*/deployment/sentinel/runtime/centos-rhel8/
    Disallow: /*/*/deployment/sentinel/runtime/centos-rhel9/
    Disallow: /*/*/deployment/sentinel/runtime/debian-ubuntu/
    Disallow: /*/*/deployment/sentinel/runtime/debian/
    Disallow: /*/*/deployment/sentinel/runtime/ubuntu/
    Disallow: /*/*/deployment/upgrade/backup/centos-rhel8/
    Disallow: /*/*/deployment/upgrade/backup/debian-ubuntu/
    Disallow: /*/*/deployment/upgrade/debian/
    Disallow: /*/*/deployment/upgrade/restore/centos-rhel8/
    Disallow: /*/*/deployment/upgrade/restore/debian-ubuntu/
    Disallow: /*/*/deployment/upgrade/rhel/
    Disallow: /*/*/deployment/deployment/time-sync.adoc
    Disallow: /*/*/operation/deep-dive/device-config-backup/centos-rhel/
    Disallow: /*/*/operation/deep-dive/device-config-backup/debian-ubuntu/
    Disallow: /*/*/operation/deep-dive/sentinel/message-broker/
    Disallow: /*/*/operation/deep-dive/sentinel/ipfix.adoc
    Disallow: /*/*/operation/deep-dive/sentinel/netflow5.adoc
    Disallow: /*/*/operation/deep-dive/sentinel/netflow9.adoc
    Disallow: /*/*/operation/deep-dive/sentinel/sflow.adoc
    Disallow: /*/*/operation/deep-dive/device-config-backup/dcb-accounts/aruba-os.adoc
    Disallow: /*/*/operation/deep-dive/device-config-backup/dcb-accounts/aruba-oscx.adoc
    Disallow: /*/*/operation/deep-dive/device-config-backup/dcb-accounts/cisco-ios.adoc
    Disallow: /*/*/operation/deep-dive/device-config-backup/dcb-accounts/juniper.adoc
    Disallow: /*/*/reference/configuration/firewall/centos-rhel/
    Disallow: /*/*/reference/configuration/firewall/debian-ubuntu/
content:
  sources:
  # Generic start page
  - url: .
    start_path: start-page
    branches: HEAD
  - url: https://github.com/Bluebird-Community/opennms.git
    start_path: docs
    branches:
      - 'develop'
    tags:
      - 'v*'
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/Bluebird-Community/grafana-plugin.git
    start_path: docs
    branches:
      - 'main-*'
      - '!main-8'
      - '!main-7'
  - url: https://github.com/Bluebird-Community/opennms-velocloud-plugin.git
    start_path: docs
    branches:
      - main
      - /^release-.*/
    tags:
      - v*
      - '!v1.0.0'
  - url: https://github.com/Bluebird-Community/opennms-provisioning-integration-server.git
    start_path: docs
    branches:
      - release-*
      - '!release-1.2*'
      - '!release-1.1*'
      - '!release-1.0*'
  - url: https://github.com/Bluebird-Community/opennms-js.git
    start_path: docs-src
    branches: develop
    tags:
    - v*
    - '!v0.*'
    - '!v1.*'
    - '!v2.0.0'
    - '!v2.0.1'
    - '!v2.0.2'
    - '!v2.5.0'
    - '!v2.5.1'
    - '!v2.5.2'
    - '!v2.5.3'
    - '!v2.5.4'
ui:
  bundle:
    url: https://github.com/Bluebird-Community/antora-ui-opennms/releases/download/v3.1.1-bluebird/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    distribution: 'Bluebird'
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
