---
runtime:
  # Set a local antora cache dir for git repositories and UI components
  cache_dir: ./.cache/antora
site:
  title: OpenNMS // Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.opennms.org
  start_page: start-page::index.adoc
  robots: allow
content:
  sources:
  # Generic start page
  - url: .
    start_path: start-page
    branches: HEAD
  - url: https://github.com/OpenNMS/opennms.git
    start_path: docs
    branches: jira/NMS-12497
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/opennms/opennms-helm.git
    start_path: docs
    branches: develop
    tags:
    - v*
    - '!v5.0.1'
    - '!v5.0.0'
    - '!v4*'
    - '!v3*'
    - '!v2*'
    - '!v1*'
  - url: https://github.com/OpenNMS/alec.git
    start_path: docs
    branches: develop
    tags: v*
  - url: https://github.com/OpenNMS/opennms-provisioning-integration-server.git
    start_path: docs
    branches:
    - master
    - release-*
    - '!release-1.1*'
    - '!release-1.0*'
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v1.3.0/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    distribution: 'Horizon'
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
