---
runtime:
  # Set a local antora cache dir for git repositories and UI components
  cache_dir: ./.cache/antora
site:
  title: OpenNMS // Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.opennms.org
  start_page: helm::index.adoc
  robots: allow
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/opennms/opennms-helm.git
    branches: develop
    start_path: docs
    tags:
    - v*
    - '!v5.0.1'
    - '!v5.0.0'
    - '!v4*'
    - '!v3*'
    - '!v2*'
    - '!v1*'
  - url: https://github.com/OpenNMS/alec.git
    branches: develop
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v1.2.0/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
