---
version: 2.1

executors:
  docs-executor:
    docker:
      - image: quay.io/bluebird/antora:3.1.1-b9
  publish-executor:
    docker:
      - image: cimg/node:21.7.3
jobs:
  build-docs:
    executor: docs-executor
    steps:
      - checkout
      - run:
          name: Prepare Node environment
          command: |
            npm install
      - run:
          name: Generate HTML output for documentation
          no_output_timeout: 30m
          command: |
            DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr npx antora --stacktrace generate antora-playbook.yml
            ./link-latest.sh
            find public ! -type d -ls | awk '{ print $NF, $0 }' | sort | cut -d' ' -f 2- > build/public-filelist.txt
      - store_artifacts:
          path: build/site.zip
          destination: site.zip
      - store_artifacts:
          path: build/public-filelist.txt
          destination: public-filelist.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/public
            - project/build
  publish-docs:
    executor: publish-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install netlify-cli dependency
          command: |
            sudo npm install -g netlify-cli
      - run:
          # NETLIFY_AUTH_TOKEN must be exposed with a token for authentication to work
          name: Push content to netlify
          command: |
            netlify deploy --site bluebird-docs --prod --auth $NETLIFY_AUTH_TOKEN -d public

workflows:
  # Triggered by every commit to this repository
  commit:
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master

  # Build and publish docs from master every night
  nightly:
    triggers:
      - schedule:
          cron: "42 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
