---
version: 2.1

executors:
  docs-executor:
    docker:
      - image: antora/antora:2.2.0
  publish-executor:
    docker:
      - image: circleci/buildpack-deps:eoan
jobs:
  build-docs:
    executor: docs-executor
    steps:
      - checkout
      - run:
          name: Generate HTML output for documentation
          command: |
            antora --stacktrace generate antora-playbook.yml
      - store_artifacts:
          path: build/site.zip
          destination: site.zip
      - persist_to_workspace:
          root: ~/
          paths:
            - project/public
            - project/build
  publish-docs:
    executor: publish-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:19:4a:22:07:4f:c1:0d:f3:fd:47:80:fb:9f:29:04"
      - attach_workspace:
          at: ~/
      - run:
          name: Install rsync dependency
          command: |
            sudo apt-get update
            sudo apt-get -y install rsync
      - run:
          name: Add SSH server fingerprint
          command: |
            echo 'docs.opennms.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMsc8yB7l3htLVhh7LEOcbxV1lus/bO5cc9BOX+2EEBtsbsPMSZVELTN1R1wFS/6watgPDwFcswfD3lUe8ymxZo=' >> ~/.ssh/known_hosts
      - run:
          name: Check connection to docs.opennms.com
          command: |
            ssh docs.opennms.com ls -l /var/www

workflows:
  build-deploy:
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master
