---
version: 2.1

executors:
  docs-executor:
    docker:
      - image: antora/antora:2.2.0
  publish-executor:
    docker:
      - image: circleci/buildpack-deps:eoan
jobs:
  build-docs:
    executor: docs-executor
    steps:
      - checkout
      - run:
          name: Generate HTML output for documentation
          command: |
            antora --stacktrace generate antora-playbook.yml
      - store_artifacts:
          path: build/site.zip
          destination: site.zip
      - persist_to_workspace:
          root: ~/
          paths:
            - project/public
            - project/build
  publish-docs:
    executor: publish-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install rsync dependency
          command: |
            sudo apt-get update
            sudo apt-get -y install rsync

workflows:
  build-deploy:
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master
